name: CodeCov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.9'
    steps:
    - uses: checkout@v3
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.9
    - name: Generate Report
      run: |
        pip install codecov
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
        codecov
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        files: /home/runner/work/feature-engine/feature_engine/coverage.xml
        flags: tests
